### ISSUE TITLE
am i doing crazy mistakes ?

### ISSUE THREAD

**Issue by muafakul** [OndrejNepozitek/ProceduralLevelGenerator-Unity#35]
Expectation : 

![image](https://user-images.githubusercontent.com/13078369/71101604-8fb01680-21e9-11ea-8bbd-a1dc3237ed15.png)

Reality :

![image](https://user-images.githubusercontent.com/13078369/71101679-b66e4d00-21e9-11ea-8ff8-54192f7984fb.png)

i failed :(

**Comment by OndrejNepozitek** [comment]
I'm sorry that it doesn't work for you. It seems that you're trying to generate platformers which are currently a very experimental feature (dungeons have better support). It looks like that there is a problem with computing the outline of the room based on the tiles in the tilemap because there are holes in the room template (not all tiles inside the room template are filled). I tried to do a quick fix which can be found [here](https://gist.github.com/OndrejNepozitek/5f89bb2c0578e42d0c9408a86f501a92).  Find the "RoomShapesLoader.cs" file and replace its content with the gist. If it works, I'll commit the changes.

Thanks for trying out the plugin and helping me find bugs.

**Comment by muafakul** [comment]
no need to sorry :D ,,maybe its just my mistakes ,,cause i m toolazy to read the documantation and only tweking your project 

____
i still failed
https://youtu.be/eeaIjeOG-XA

**Comment by OndrejNepozitek** [comment]
There may be a problem with Room 6. The marked tiles in the picture below have only diagonal neighbours.

![image](https://user-images.githubusercontent.com/2265359/71110569-d725ab00-21c7-11ea-8f3e-bb3189a328d4.png)

You also need to provide the tiles marked in black.

![image](https://user-images.githubusercontent.com/2265359/71110809-4d2a1200-21c8-11ea-8b00-158e22d49197.png)

**Comment by muafakul** [comment]
You're doing a great job ,,extremly thanks man 💃 

![image](https://user-images.githubusercontent.com/13078369/71111576-5634d680-21fc-11ea-8985-440d37dafde0.png)
