### ISSUE TITLE
is there any way to auto update the generated map when we do a changes to a prefabs inside room template folder ?

### ISSUE THREAD

**Issue by muafakul** [OndrejNepozitek/ProceduralLevelGenerator-Unity#36]
i hope there is some way

**Comment by OndrejNepozitek** [comment]
What changes do you have in mind?

If you change the inside of a room template, you can then run the generator with the same seed and it will generate the same map (the seed is printed in the console after a layout is generated and you can set it in the PayloadInitializer). However, this may not be possible if you change the outline of the room template or its door positions, because then the algorithm can work differently even with the same seed.

**Comment by muafakul** [comment]
imean , i make room template as AB , then generate it in scene1 , then i generate another map on other scene ,,,,,,,,,,,


but when i what to change the room template as AZ ,,, ,, how to make it auto updated to AZ  in scene1 and other scene ,,,,,,,,,,,,, or the only way is i re generate in each scene ?

**Comment by OndrejNepozitek** [comment]
I'm afraid it's not possible to propagate such changes to already generated maps.

**Comment by muafakul** [comment]
ah ok ,
