### ISSUE TITLE
How to change the structure of layers in room templates?

### ISSUE THREAD

**Issue by longtran2904** [OndrejNepozitek/ProceduralLevelGenerator-Unity#48]
I wanted to change the order and add some layers to the room templates like:
background 1: order 0
background 2: order 1
walls: order 2 (collider)
collideable: order 3
other 1, 2, 3: ...
And i also wanted my collider to not use Composite by default and also added some gameobject.
How to do that? I didn't understand the docs well.

**Comment by OndrejNepozitek** [comment]
You want to add a GameObject to the room template after it is created?

**Comment by longtran2904** [comment]
What i want is when you go to Create/Dungeon generator/Dungeon room template it will:
1. Have my custom layers' structure
2. Has my predefined custom gameobject

**Comment by OndrejNepozitek** [comment]
So you can find the files that you need to modify in this [gist](https://gist.github.com/OndrejNepozitek/006e692fe9e421cc6764210f90a817a8).

First, you have to create a custom TilemapLayersHandler. This class is responsible for creating the structure of tilemaps both when a room template is created and when the dungeon generator initializes the whole level. You need to implement the "InitializeTilemaps()" method. You can look at the file in the gist. You can create any structure of tilemaps in this method. Just make sure that you first add the Grid component to the gameobject argument and that every tilemap layer is a child gameobject. If you want to correctly render the generated dungeon, don't forget to add the TilemapRenderer component to each tilemap layer.

Next we have to register this TilemapLayersHandler in the generator. First we have to create an instance of the ScriptableObject via a custom menu item (Dungeon generator/Custom tilemap layers handler). And then drag and drop this scriptableobject to the Tilemap Layers Handler field in the Dungeon generator component. Now everytime a dungeon is generator, your custom tilemap layers handler is used.

Next we need to create a custom RoomTemplateInitializer (the second file in the gist). In the InitializeTilemaps method we have to call our new TilemapLayersHandler to initialize tilemaps. And if you want to add any custom gameObject to the room template, put that logic into the Initialize() method after "base.Initialize();".

And the last thing we need to do is to create a custom menu item that will create the room template for us. That's the part of the RoomTemplateInitializer that's wrapped in "#if UNITY_EDITOR". It'll create a new menu item "Assets/Create/Dungeon generator/Custom room template". So if you want to use your new room template structure, you need to use this new menu item instead of the origin room template creator.

Everything should be ready now. I'll try to improve this process for the next version of the plugin so that it's easier to do. And I should also properly document that.

P.S. Make sure that you do not combine room templates with different tilemap layers because the generator won't know how to handle that.

**Comment by longtran2904** [comment]
Thanks you for the answer. I finally figured it out. The directory for the namespace was wrong so i fixed it. For anyone who might interested in making something like this here is my code in this [gist](<script src="https://gist.github.com/longtran2904/7fa924c1770dff91b5c0828fa0cdbb7f.js"></script>).

Custom layers: (all colliders don't have composite and rigidbody)
Background 1: order 0
Background 2: order 1
Walls: order 2 (collider)
Collideable: order 3 (collider)
Other 1, 2: order 4, 5

Custom Room Template: In addition to the normal template, it has a Lights, Camera Info and Enemies gameobject with custom components.

**Comment by longtran2904** [comment]
I have a small question: How to make unity to add me name the file when i created it?

**Comment by OndrejNepozitek** [comment]
Unfortunately, I don't know whether that's possible. I tried googling that but didn't find anything useful. It seems like it would be possible if we tried to save an Asset that is not a GameObject prefab (https://answers.unity.com/questions/480226/select-asset-for-rename.html?_ga=2.82518929.660938378.1587902501-61295266.1573113939).

**Comment by longtran2904** [comment]
Ok. Thanks for replying.

**Comment by OndrejNepozitek** [comment]
So I came up with a **VERY HACKY** solution to this. I create the prefab the old way, read its raw content, delete the prefab and then use the ProjectWindowUtil.CreateAssetWithContent() method to save the prefab manually with a name prompt. I'm not sure if it doesn't have some nasty side effects but it seems working. 

Let me know if it works for you if you decide to try it.

```csharp
        [MenuItem("Assets/Create/Dungeon generator/Custom room template")]
        public static void CreateCustomRoomTemplate()
        {
            // Create empty game object
            var roomTemplate = new GameObject();

            // Add room template initializer, initialize room template, destroy initializer
            // ONLY THIS LINE HAS TO BE CHANGED if we want to add a menu item with a different RoomTemplateInitializer
            var roomTemplateInitializer = roomTemplate.AddComponent<CustomRoomTemplateInitializer>();
            roomTemplateInitializer.Initialize();
            Object.DestroyImmediate(roomTemplateInitializer);

            var currentPath = GetCurrentPath();

            // Save prefab to temporary file
            var name = AssetDatabase.GenerateUniqueAssetPath(currentPath + "/tmp.prefab");
            var prefab = PrefabUtility.SaveAsPrefabAsset(roomTemplate, name);

            // Load prefab content manually
            var rawPrefabContent = File.ReadAllText(name);

            // Destroy original game object
            Object.DestroyImmediate(roomTemplate);

            // Destroy temp prefab
            AssetDatabase.ReleaseCachedFileHandles();
            File.Delete(name);
            File.Delete(name + ".meta");
            AssetDatabase.Refresh();

            // Save prefab content manually
            // This method will prompt rename of the created file
            ProjectWindowUtil.CreateAssetWithContent(AssetDatabase.GenerateUniqueAssetPath(currentPath + "/Room template.prefab"), rawPrefabContent);
        }
```

**Comment by longtran2904** [comment]
Hey, i got this error: Timeout was reach when generated level again. It sometime happend sometime didn't after i changed the custom structure.
Here is the json file of the map: 
[exportedMapDescription.txt](https://github.com/OndrejNepozitek/ProceduralLevelGenerator-Unity/files/4535738/exportedMapDescription.txt)
If you can look at it i will be really appriciate alot

Here is the graph: 
![image](https://user-images.githubusercontent.com/53656110/80312377-19fb2d80-880f-11ea-8f63-738dc79c6ba6.png)

**Comment by longtran2904** [comment]
Oh, plz forgive me i was so stupid, i just added the wrong doors for a room. Sorry!

**Comment by longtran2904** [comment]
Sorry for reopening this issue but there was a bug that was really annoying. When i created a custom tilemap layer handler in the project view (Create\Dungeon generator\Custom tilemap la...) and then assign it into the input field for it in Post processing config, it would work normally. But after a script was compiled or i reopened the project or just loaded the scene from another scene it would be unusable. I couldn't assign it to the field and unity said something like: "The associated script can not be load. Plz fix any compile error...." when i looked into the file. The solution i came up with was just create a new file and assign it but it would still have that problem.

**Comment by OndrejNepozitek** [comment]
And was there any compile error that needed to be fixed?

**Comment by longtran2904** [comment]
NO

**Comment by longtran2904** [comment]
I also noticed that the script is in the namespace Assets.Script, does that neccesary.

**Comment by longtran2904** [comment]
You can see my script here, i also posted this above. It has 2 files: https://gist.github.com/longtran2904/7fa924c1770dff91b5c0828fa0cdbb7f

**Comment by OndrejNepozitek** [comment]
Please make sure that the name of the file is the same as the name of the script. Because I noticed that in your gist the file is named "CustomTilemapLayersHandler.cs", but the class is named "CustomTilemapsLayersHandler" (with an additional "s" after "Tilemap"). Unity does not like thag.

**Comment by longtran2904** [comment]
Okay i changed it and it worked well for now. Thank you
